import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Building2, CircleDollarSign, MapPin, Search, TrendingUp } from 'lucide-react';
import { useProblemStore } from '../../store/problemStore';
import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';

export default function IndustryTracking() {
  const { problems, fetchProblems } = useProblemStore();
  const [query, setQuery] = useState('');
  useEffect(() => { fetchProblems(); }, [fetchProblems]);
  const projects = useMemo(() => problems.filter((p) => `${p.title} ${p.description} ${p.assignedInstitution || ''}`.toLowerCase().includes(query.toLowerCase())), [problems, query]);

  return <div className="min-h-screen bg-[#0F1B1E] text-[#F2EFE9] p-6 max-w-7xl mx-auto space-y-7"><header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 border-b border-[#1D3238] pb-6"><div><div className="inline-flex items-center gap-2 text-xs font-mono text-[#E8A33D] mb-2"><Building2 size={14} /> CSR IMPACT PORTFOLIO</div><h1 className="text-3xl font-bold font-display">Problem Tracking</h1><p className="text-sm text-[#9BA8A6] mt-2">Follow funded civic projects from technical ownership through measurable field impact.</p></div><div className="grid grid-cols-2 gap-2 text-center text-xs"><div className="bg-[#16262A] border border-[#1D3238] rounded-lg px-4 py-3"><b className="block text-lg text-[#E8A33D]">₹4.5L</b>Committed</div><div className="bg-[#16262A] border border-[#1D3238] rounded-lg px-4 py-3"><b className="block text-lg text-[#2F9E8F]">08</b>Projects</div></div></header><div className="relative"><Search size={16} className="absolute left-3 top-3 text-[#9BA8A6]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search your supported projects" className="w-full bg-[#16262A] border border-[#1D3238] rounded-lg py-2.5 pl-9 pr-3 text-sm" /></div><div className="space-y-3">{projects.map((project) => <article key={project.id} className="bg-[#16262A] border border-[#1D3238] rounded-xl p-5"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="space-y-2"><div className="flex items-center gap-2"><span className="text-xs font-mono text-[#9BA8A6]">{project.id}</span><Badge status={project.status} /></div><h2 className="font-bold">{project.title}</h2><p className="text-sm text-[#9BA8A6] line-clamp-2">{project.description}</p><div className="flex flex-wrap gap-4 text-xs text-[#9BA8A6]"><span className="flex items-center gap-1"><MapPin size={13} /> {project.location?.district || 'Jharkhand'}</span><span className="flex items-center gap-1"><TrendingUp size={13} /> Impact reporting active</span></div></div><div className="flex items-center gap-3"><div className="text-right"><span className="text-xs text-[#9BA8A6]">Grant allocated</span><p className="font-bold text-[#E8A33D]">₹45,000</p></div><Link to={`/problem/${project.id}`}><Button variant="outline" className="text-xs py-2"><CircleDollarSign size={14} /> View impact</Button></Link></div></div></article>)}</div></div>;
}
